# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  gitversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '6.0.0'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

  test-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
    - uses: actions/cache@v4
      id: go-cache
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - name: Install dependencies
      if: steps.go-cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: Run Tests
      run: go test -timeout 30s ./pkg/server
  test-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
    - uses: actions/cache@v4
      id: go-cache
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - name: Install dependencies
      if: steps.go-cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: Run Tests
      run: go test -timeout 30s ./pkg/client
  test-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
    - uses: actions/cache@v4
      id: go-cache
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - name: Install dependencies
      if: steps.go-cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: Run Tests
      run: go test -timeout 30s ./pkg/files

  build:
    strategy:
      matrix:
        go-arch: ['ARM64', 'AMD64']
        go-os: ['linux', 'darwin', 'windows']
    runs-on: ubuntu-latest
    needs:
      - "test-server"
      - "test-client"
      - "test-files"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - uses: actions/cache@v4
        id: go-cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Convert to lowercase
        id: tolower
        run: INPUT=${{ env.VAR_UPPERCASE }}; echo "toLower=${INPUT,,}">>${GITHUB_OUTPUT}

      - name: Build
        run: |
          go build -o bin/file-replicator-${{ matrix.go-os }}-${{ matrix.go-go-arch.toLower }}-${{ needs.gitversion.outputs.semver }} main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/
